In [1]:
import numpy as n

ModuleNotFoundError: No module named 'numpy'

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
print(np.__version__)
np.show_config()

1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
Z = np.arange(10, 50) #创建一个值域范围从10到49的向量(
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
Z = np.arange(50)
Z = Z[::-1]#反转一个向量(第一个元素变为最后一个)
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
#创建一个 3x3 并且值从0到8的矩阵
Z = np.arrange(9).reshape(3,3)
print(Z)

AttributeError: module 'numpy' has no attribute 'arrange'

In [13]:
#创建一个 3x3 并且值从0到8的矩阵
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [15]:
#创建一个 3x3 的单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#创建一个 3x3x3的随机数组
Z = np.random.random((3,3,3))
print(Z)

[[[0.58628937 0.71503679 0.69731216]
  [0.44067817 0.46748404 0.16805045]
  [0.63795795 0.86773682 0.02232184]]

 [[0.66594462 0.7966867  0.50434   ]
  [0.13839654 0.20152254 0.26685805]
  [0.15038125 0.34574646 0.25858995]]

 [[0.05883405 0.78657647 0.85727566]
  [0.12066524 0.51224041 0.77705892]
  [0.95221052 0.09831322 0.2164009 ]]]


In [17]:
#创建一个 10x10 的随机数组并找到它的最大值和最小值
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin,Zmax)

0.011762503914266031 0.9940310303839898


In [18]:
#  创建一个长度为30的随机向量并找到它的平均值 
Z = np.random.random(30)
m = Z.mean()
print(m)

0.560767722128711


In [19]:
# 创建一个二维数组，其中边界值为1，其余值为0
Z = np.ones((10, 10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_value=0)
print(Z)

ValueError: constant_value keyword not in allowed keywords ['constant_values']

In [21]:
#对于一个存在在数组，如何添加一个用0填充的边界?
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [22]:
#以下表达式运行的结果分别是什么? 
#0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1

In [23]:
print(0*nan)

NameError: name 'nan' is not defined

In [24]:
print(0 * np.nan)

nan


In [25]:
print(np.nan == np.nan)

False


In [26]:
print(np.inf > np.nan)

False


In [27]:
print(np.nan - np.nan)

nan


In [28]:
print(0.3 == 3 * 0.1)

False


In [29]:
#创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
Z = np.diag(1+np.arange(4), k=-1)#k为偏移量,正数往上偏，负数往下偏
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [32]:
#创建一个8x8 的矩阵，并且设置成棋盘样式
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1 #1::2的意思是 从索引1开始到末尾，间隔为2
print(Z)
print("\n棋盘格式:")
Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]

棋盘格式:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [33]:
#考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [35]:
#用tile函数去创建一个 8x8的棋盘样式矩阵
Z = np.tile(np.array([[0,1],[1,0]]), (4,4)) #tile函数就是对原数组进行横向纵向的复制(第二个参数)
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [36]:
#对一个5x5的随机矩阵做归一化 (提示: (x - min) / (max - min))
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[5.65742718e-01 6.82598187e-01 8.82152497e-01 7.87892917e-01
  5.28752304e-01]
 [6.44775195e-01 9.61001305e-01 3.38329604e-01 4.10399227e-01
  8.54510016e-01]
 [1.68465594e-01 8.96309452e-01 5.57945234e-01 0.00000000e+00
  8.28466716e-01]
 [7.76797787e-01 7.43066733e-01 1.14791212e-01 3.30188541e-04
  4.87737290e-01]
 [9.30157450e-01 7.25684515e-01 9.39130343e-01 1.00000000e+00
  8.32806689e-01]]


In [37]:
#创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)
                 ])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [38]:
# 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [40]:
#给定一个一维数组，对其在3到8之间的所有元素取反
Z = np.arange(11)
Z[(3 <= Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [41]:
#下面脚本运行后的结果是什么?  (提示: np.sum)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [44]:
#考虑一个整数向量Z,下列表达合法的是哪个?
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z

In [45]:
Z = np.arange(5)
Z ** Z

array([  1,   1,   4,  27, 256], dtype=int32)

In [46]:
Z = np.arange(5)
2 << Z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [47]:
Z = np.arange(5)
Z < -Z

array([False, False, False, False, False])

In [53]:
Z = np.arange(5)
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [55]:
# Z = np.arange(5)
# Z < Z > Z  #false

In [56]:
#下列表达式的结果分别是什么?
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

In [58]:
print(np.array(0) / np.array(0))

nan


c:\program files\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [59]:
print(np.array(0) // np.array(0))

0


c:\program files\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [62]:
#如何从零位对浮点数组做舍入 ?(提示: np.uniform, np.copysign, np.ceil, np.abs)

Z = np.random.uniform(-10, +10, 10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[ 1.05664697  5.84935308 -7.29171247 -2.65638353  8.73771568 -3.98361543
  5.70623163  5.05497779 -9.97974746  3.50354195]
[  2.   6.  -8.  -3.   9.  -4.   6.   6. -10.   4.]


In [66]:
#如何找到两个数组中的共同元素?

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

print(np.intersect1d(Z1, Z2))

[0 3 6 7]


In [70]:
#  如何忽略所有的 numpy 警告(尽管不建议这么做)? (提示: np.seterr, np.errstate)
# Sucide mode on
defaults = np.seterr(all = 'ignore')
z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [60]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [71]:
# 下面的表达式是正确的吗?
# np.sqrt(-1) == np.emath.sqrt(-1)  # False

In [75]:
# 如何得到昨天，今天，明天的日期?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("Yesterday is "+ str(yesterday))
print("Today is "+str(today))
print("tomorrow is "+ str(tomorrow))

TypeError: Invalid datetime unit "S" in metadata

In [79]:
#如何得到所有与2016年7月对应的日期？
Z = np.arange('2016-07', '2016-08',dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31' '2016-08-01' '2016-08-02' '2016-08-03' '2016-08-04'
 '2016-08-05' '2016-08-06' '2016-08-07' '2016-08-08' '2016-08-09'
 '2016-08-10' '2016-08-11' '2016-08-12' '2016-08-13' '2016-08-14'
 '2016-08-15' '2016-08-16' '2016-08-17' '2016-08-18' '2016-08-19'
 '2016-08-20' '2016-08-21' '2016-08-22' '2016-08-23' '2016-08-24'
 '2016-08-25' '2016-08-26' '2016-08-27' '2016-08-28' '2016-08-29'
 '2016-08-30' '2016-08-31']


In [87]:
#如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)

array([3., 3., 3.])

In [88]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [89]:
np.negative(A, out=A)

array([-0.5, -0.5, -0.5])

In [91]:
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [98]:
#用五种不同的方法去提取一个随机数组的整数部分
Z = np.random.uniform(0, 10, 10) #最后一个１０是长度
print(Z)

[8.23458432 5.08616971 6.66883357 2.06004505 2.11902885 3.92778747
 1.05479144 5.61363628 9.29943388 4.42393932]


In [99]:
print(Z - Z % 1)

[8. 5. 6. 2. 2. 3. 1. 5. 9. 4.]


In [100]:
print(np.floor(Z))

[8. 5. 6. 2. 2. 3. 1. 5. 9. 4.]


In [102]:
print(np.ceil(Z)-1)

[8. 5. 6. 2. 2. 3. 1. 5. 9. 4.]


In [104]:
print(Z.astype(int))

[8 5 6 2 2 3 1 5 9 4]


In [106]:
print(np.trunc(Z))

[8. 5. 6. 2. 2. 3. 1. 5. 9. 4.]


In [107]:
# 创建一个5x5的矩阵，其中每行的数值范围从0到4 
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [108]:
#通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [110]:
#创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 
Z = np.linspace(0, 1, 11, endpoint=False)[1:] #endpoint用来过滤1,后面的切片用来过滤０
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [112]:
#创建一个长度为10的随机向量，并将其排序 
Z = np.linspace(0, 1, 11,endpoint=False)[1:]
Z.sort()
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [114]:
#.对于一个小数组，如何用比 np.sum更快的方式对其求和？
Z = np.arange(10)
np.add.reduce(Z)

45

In [120]:
# 对于两个随机数组A和B，检查它们是否相等(

# 方法１
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)

# 方法二
equal = np.array_equal(A, B)
print(equal)

False
False


In [121]:
#创建一个只读数组(read-only) (
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [122]:
# 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式 (hint: np.sqrt, np.arctan2)
Z = np.random.random((10, 2))

X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)# p
T = np.arctan2(Y, X) #xita
print(R)
print(T)

[0.23733927 1.13721545 0.89328462 0.94774843 0.27139872 1.22437176
 1.12621728 0.58304571 0.91061138 0.14994507]
[0.05509034 1.05988611 1.4966613  0.86073482 1.34453869 0.80835092
 1.08939919 0.01346203 1.32186425 0.70514653]


In [123]:
# 创建一个长度为10的向量，并将向量中最大值替换为1
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.66178698 0.38930375 0.73228039 0.46435608 0.21608487 0.67574416
 0.46931952 0.72812403 0.7303265  0.        ]


In [125]:
# 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 
# (提示: np.meshgrid)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [128]:
#给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj)) 
#(提示: np.subtract.outer)
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [131]:
#打印每个numpy标量类型的最小值和最大值？
# (提示: np.iinfo, np.finfo, eps)
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


In [135]:
# 如何打印一个数组中的所有数值? 
# (提示: np.set_printoptions)
# np.set_printoptions(threshold=np.nan)
# Z = np.zeros((16,16))
# print (Z)


In [136]:
# 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

45
